# Actor-RTC 辅助服务配置文件模板
# 此文件由 config crate 的 build.rs 自动生成
# 请根据实际部署环境修改相应的配置值

enable = 15

name = "actrix-default"

env = "dev"

# user = "actrix"

# group = "actrix"

# pid = "logs/actrix.pid"


[bind]
# [bind.http]
# domain_name = "localhost"
# advertised_ip = "127.0.0.1"
# ip = "0.0.0.0"
# port = 8080

# [bind.https]
# domain_name = "localhost"
# advertised_ip = "127.0.0.1"
# ip = "0.0.0.0"
# port = 8443
# cert = "certificates/server.crt"
# key = "certificates/server.key"


[bind.ice]
domain_name = "localhost"

ip = "0.0.0.0"

port = 3478




[turn]
advertised_ip = "127.0.0.1"

advertised_port = 3478

relay_port_range = "49152-65535"

realm = "actor-rtc.local"


location_tag = "default-location"

# [supervisor]
# connect_timeout_secs = ""
# status_report_interval_secs = ""
# health_check_interval_secs = ""
# enable_tls = ""
# tls_domain = ""
# client_cert = ""
# client_key = ""
# ca_cert = ""
# max_clock_skew_secs = ""
# [supervisor.supervisord]
# node_name = "actrix-node"
# ip = "0.0.0.0"
# port = 8080
# advertised_ip = "127.0.0.1"
# [supervisor.client]
# node_id = ""
# endpoint = "http://localhost:50051"
# shared_secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"


[services]
# ks = ""

# [services.ais]
# [services.ais.server]
# signaling_heartbeat_interval_secs = ""
# token_ttl_secs = ""
# [services.ais.dependencies]
# ks = ""

# [services.signaling]
# [services.signaling.server]
# ws_path = ""
# [services.signaling.server.rate_limit]
# [services.signaling.server.rate_limit.connection]
# enabled = ""
# per_minute = ""
# burst_size = ""
# max_concurrent_per_ip = ""
# [services.signaling.server.rate_limit.message]
# enabled = ""
# per_second = ""
# burst_size = ""
# [services.signaling.dependencies]
# ks = ""
# ais = ""


sqlite_path = "database"

actrix_shared_key = "CHANGE_ME_32_CHAR_RANDOM_KEY_HERE"


[observability]
filter_level = "info"


[observability.log]
output = "console"

rotate = false

path = "logs/"



[observability.tracing]
enable = false

service_name = "actrix"

endpoint = "http://127.0.0.1:4317"



